config/routes.rb
# frozen_string_literal: true

def user?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && !warden_req.user.advisor?
end

def advisor?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && warden_req.user.advisor?
end

Rails.application.routes.draw do
  resources :semesters, only: :update

  resources :majors do
    resources :curriculum_categories, except: :index
  end

  resources :courses do
    resources :offerings, except: :show
  end

  namespace :offerings do
    post :import
  end

  devise_for :users, controllers: {
    registrations: :registrations, sessions: :sessions
  }
  devise_scope :user do
    authenticated :user do
      root "work_schedules#index", constraints: ->(request) { user?(request) }
      root "users#index", constraints: ->(request) { advisor?(request) }
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :transcripts, only: %i(index create destroy new),
                          path: :transcript
  resources :work_schedules, only: %i(create index destroy), path: :calendar
  resources :schedules, only: %i(index create destroy), path: :schedule

  resources :users, only: %i(index show) do
    resources :schedule_approvals, only: %i(create update)
  end
end

app/models/offering.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: offerings
#
#  id           :integer          not null, primary key
#  course_id    :integer
#  days_time_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#  semester_id  :integer
#  section      :string(255)
#

class Offering < ApplicationRecord
  include SemesterHelpers

  belongs_to :days_time
  belongs_to :user
  belongs_to :course

  validates :course, uniqueness: {
    scope: %i(days_time user semester_id),
    message: "This is already being offered!"
  }
  validates :course, presence: { message: "A course must be selected!" }
  validates :days_time, presence: { message: "A time slot must be selected!" }
  validates :user, presence: { message: "A professor must be selected!" }
  validates :section, presence: true

  scope :has_meeting_time, lambda {
    joins(:days_time).merge(DaysTime.has_meeting_time)
  }

  delegate :time_range, :meeting_time?, :days, :overlaps?, :overlaps_any?,
           to: :days_time

  def display
    "#{days_time.days} from #{display_time} with #{user.professor}"
  end

  def display_time
    return if days_time.start_time.blank?

    days_time.start_time.strftime("%l:%M") + " -" +
      days_time.end_time.strftime("%l:%M")
  end

  class << self
    def import(file)
      CSV.foreach(file.path) do |row|
        course   = csv_get_course(row)
        prof     = csv_get_prof(row)
        day_time = csv_get_day_time(row)
        offering = new(user: prof, days_time: day_time, course: course,
                       section: row[2])
        offering.save if offering.valid?
      end
    end

    # CSV parse helper methods
    def csv_get_course(row)
      Course.find_by(
        subject: row[1].split[0].upcase, course: row[1].split[1].to_i
      )
    end

    def csv_get_prof(row)
      prof = row[12].split(",")
      if prof[1].blank?
        User.find_by(first_name: nil)
      else
        last_name  = prof[0].strip.downcase
        first_name = prof[1].strip.downcase
        User.find_by("lower(last_name) = ? AND lower(first_name) = ?",
                     last_name, first_name)
      end
    end

    def csv_get_day_time(row)
      if row[7].blank?
        csv_get_offsite(row)
      else
        DaysTime.find_by(
          days: row[7].upcase, start_time: convert_to_time(row[8]),
          end_time: convert_to_time(row[9]),
        )
      end
    end

    def csv_get_offsite(row)
      if row[2][0].casecmp("w").zero?
        DaysTime.find_by(days: "ONLINE")
      elsif row[2][0].casecmp("x").zero?
        DaysTime.find_by(days: "OFFSITE")
      end
    end

    def convert_to_time(time)
      Time.strptime("2001-01-01 #{time} +0000", "%Y-%m-%d %I%M%p %z")
    end
  end
end

app/models/transcript.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: transcripts
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  course_id     :integer
#  created_at    :datetime
#  updated_at    :datetime
#  grade_c_minus :boolean
#  grade_c       :boolean
#

class Transcript < ApplicationRecord
  GRADES = %w(A A- B+ B B- C+ C C- D+ D D- F).freeze

  belongs_to :user
  belongs_to :course

  validates :course, uniqueness: {
    scope: :user, message: "You've already taken this course!"
  }, presence: { message: "A course must be selected!" }
end

app/controllers/offerings_controller.rb
# frozen_string_literal: true

class OfferingsController < ApplicationController
  before_action :set_course, except: :import
  before_action :set_offering, only: %i(destroy edit update)
  authorize_resource

  def index
    @offerings = semester_offerings
  end

  def new
    @offering = semester_offerings.new
  end

  def edit
  end

  def create
    @offering = semester_offerings.new(offering_params)

    if @offering.save
      redirect_to course_offerings_path(@course),
                  notice: "Offering was successfully created!"
    else
      render :new
    end
  end

  def update
    if @offering.update(offering_params)
      redirect_to course_offerings_path, notice: "Offering updated!"
    else
      render :new
    end
  end

  def destroy
    @offering.destroy
    Schedule.where(offering: @offering).delete_all

    redirect_to course_offerings_path(@course),
                notice: "Offering was successfully deleted!"
  end

  def import
    Offering.import(params[:offering_file])

    redirect_to courses_path, notice: "Offerings Uploaded!"
  end

  private

  def set_offering
    @offering = semester_offerings.find(params[:id])
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

  def semester_offerings
    @semester_offerings ||= @course.offerings.for_semester(current_semester)
  end

  def offering_params
    params.require(:offering).permit(:days_time_id, :user_id, :section)
  end
end

app/views/offerings/_form.haml
= form_for [course, offering], html: { class: "layout vertical center mt-3" } do |f|
  = f.collection_select :days_time_id,
      DaysTime.all, :id, :pretty_day_time,
      prompt: "Choose a Day and Time", class: "mb-4"

  = f.collection_select :user_id,
      User.offering_advisors, :id, :professor,
      prompt: "Choose a Professor"

  = f.text_field :section, label: "Section Number",
      minlength: 2, help_text: "Ex: W1, 02, etc", required: true

  = f.submit

app/views/offerings/_form.html.haml
= form_for [course, offering], html: { class: "layout vertical center mt-3" } do |f|
  = f.collection_select :days_time_id,
      DaysTime.all, :id, :pretty_day_time,
      prompt: "Choose a Day and Time", class: "mb-4"

  = f.collection_select :user_id,
      User.offering_advisors, :id, :professor,
      prompt: "Choose a Professor"

  = f.text_field :section, label: "Section Number",
      minlength: 2, help_text: "Ex: W1, 02, etc", required: true

  = f.submit

app/views/offerings/_upload.haml
%aside.mdc-dialog#upload-offerings-dialog{ aria: { describedby: "upload-offerings-description",
  hidden: true, labelledby: "upload-offering-heading", role: :alertdialog } }
  = form_tag offerings_import_path, multipart: true, class: "mdc-dialog__surface" do
    %header.mdc-dialog__header
      %h2.mdc-dialog__header__title#upload-offering-heading
        Import Offerings
    %section.mdc-dialog__body#upload-offerings-description
      %h3.mdc-typography--subheading2.center-text.my-1
        Upload a .CSV formatted:
      .layout.vertical.start.instructions.m-0
        %p.m-0.mdc-typography--body1 Column 2 - The course formatted: CSC 110 Name
        %p.m-0.mdc-typography--body1 Column 3 - Course section
        %p.m-0.mdc-typography--body1 Column 8 - Days being offered(MWF, TR, etc.)
        %p.m-0.mdc-typography--body1 Column 9 - Start time formatted: 0330PM
        %p.m-0.mdc-typography--body1 Column 10 - End time formatted: 0330PM
        %p.m-0.mdc-typography--body1 Column 13 - Professor formmatted: "last, first"
        = file_field_tag :offering_file, accept: ".csv", class: "hidden"
    %footer.mdc-dialog__footer
      %button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--cancel
        Cancel
      %button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--accept.choose-file
        Choose File
  .mdc-dialog__backdrop

app/views/offerings/_upload.html.haml
%aside.mdc-dialog#upload-offerings-dialog{ aria: { describedby: "upload-offerings-description",
  hidden: true, labelledby: "upload-offering-heading", role: :alertdialog } }
  = form_tag offerings_import_path, multipart: true, class: "mdc-dialog__surface" do
    %header.mdc-dialog__header
      %h2.mdc-dialog__header__title#upload-offering-heading
        Import Offerings
    %section.mdc-dialog__body#upload-offerings-description
      %h3.mdc-typography--subheading2.center-text.my-1
        Upload a .CSV formatted:
      .layout.vertical.start.instructions.m-0
        %p.m-0.mdc-typography--body1 Column 2 - The course formatted: CSC 110 Name
        %p.m-0.mdc-typography--body1 Column 3 - Course section
        %p.m-0.mdc-typography--body1 Column 8 - Days being offered(MWF, TR, etc.)
        %p.m-0.mdc-typography--body1 Column 9 - Start time formatted: 0330PM
        %p.m-0.mdc-typography--body1 Column 10 - End time formatted: 0330PM
        %p.m-0.mdc-typography--body1 Column 13 - Professor formmatted: "last, first"
        = file_field_tag :offering_file, accept: ".csv", class: "hidden"
    %footer.mdc-dialog__footer
      %button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--cancel
        Cancel
      %button.mdc-button.mdc-dialog__footer__button.mdc-dialog__footer__button--accept.choose-file
        Choose File
  .mdc-dialog__backdrop

app/views/offerings/edit.html.haml
:ruby
  content_for :title, "Edit Offering"
  content_for :back_url, course_offerings_path(@course)
  content_for :active_tab, :courses

= render "form", course: @course, offering: @offering

app/views/offerings/index.html.haml
- content_for :title, "#{@course.condensed_course} Offerings"
- content_for :back_url, course_path(@course)
- content_for :toolbar do
  - if can?(:import, Offering)
    = material_icon.file_upload.css_class("upload-offerings")
- content_for :active_tab, :courses

.layout.vertical.center
  .mdc-card.mt-2.container.white
    %section.mdc-card__primary
      %h1.mdc-card__title.mdc-card__title--large Offerings
    %section.mdc-card__supporting-text
      %ul.mdc-list
        - @offerings.each do |offering|
          %li.mdc-list-item
            %span.mdc-list-item__text
              %span.mdc-list-item__text__primary
                #{offering.section}-#{offering.user.professor}
              %span.mdc-list-item__text__primary.mdc-typography--caption
                = offering.days_time.pretty_day_time
            .mdc-list-item__end-detail.relative
              = material_icon.more_vert.css_class("menu-toggle")
              .mdc-simple-menu.offerings-simple-menu{ tabindex: -1 }
                .mdc-simple-menu__items.mdc-list{ "aria-hidden" => true, role: :menu }
                  = link_to edit_course_offering_path(@course, offering),
                      class: "mdc-list-item", role: :menuitem, tabindex: 0 do
                    = material_icon.mode_edit.css_class("mr-2")
                    Edit
                  = link_to course_offering_path(@course, offering),
                      class: "mdc-list-item", method: :delete,
                      data: { confirm: "Are you sure?" }, role: :menuitem,
                      tabindex: 0 do
                    = material_icon.delete.css_class("mr-2")
                    Delete

= fab new_course_offering_path(@course)

= render "offerings/upload"

app/views/offerings/new.html.haml
- content_for :title, "New Offering"
- content_for :back_url, course_offerings_path(@course)
- content_for :toolbar do
  - if can?(:import, Offering)
    = material_icon.file_upload.css_class("upload-offerings")
- content_for :active_tab, :courses

= render "form", course: @course, offering: @offering

= render "offerings/upload"