config/routes.rb
# frozen_string_literal: true

def user?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && !warden_req.user.advisor?
end

def advisor?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && warden_req.user.advisor?
end

Rails.application.routes.draw do
  resources :semesters, only: :update

  resources :majors do
    resources :curriculum_categories, except: :index
  end

  resources :courses do
    resources :offerings, except: :show
  end

  namespace :offerings do
    post :import
  end

  devise_for :users, controllers: {
    registrations: :registrations, sessions: :sessions
  }
  devise_scope :user do
    authenticated :user do
      root "work_schedules#index", constraints: ->(request) { user?(request) }
      root "users#index", constraints: ->(request) { advisor?(request) }
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :transcripts, only: %i(index create destroy new),
                          path: :transcript
  resources :work_schedules, only: %i(create index destroy), path: :calendar
  resources :schedules, only: %i(index create destroy), path: :schedule

  resources :users, only: %i(index show) do
    resources :schedule_approvals, only: %i(create update)
  end
end

app/models/schedule.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules
#
#  id          :integer          not null, primary key
#  offering_id :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  semester_id :integer
#

class Schedule < ApplicationRecord
  include SemesterHelpers

  belongs_to :offering
  belongs_to :user

  has_one :course, through: :offering
  has_one :days_time, through: :offering

  validates :offering, uniqueness: { scope: %i(user_id semester_id) }
  validate do
    errors.add(:base, "You cannot take more than 18 credits") if
      user.credits(semester_id) > 18
  end
  validate do
    errors.add(:base, "You've already scheduled for that course") if
      user.courses.where(
        offerings: { course_id: offering.course_id },
        schedules: { semester_id: semester_id }
      ).exists?
  end
end

app/models/schedule/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedule_categories
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  curriculum_category_id :integer
#  semester_id            :integer
#  completed              :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Schedule
  class Category < ApplicationRecord
    include SemesterHelpers

    belongs_to :user
    belongs_to :curriculum_category

    has_many :category_courses, dependent: :destroy
    has_many :courses, through: :category_courses
    has_many :category_offerings, dependent: :destroy
    has_many :offerings, through: :category_offerings
    has_many :visible_category_offerings, -> { where(hidden: false) },
             class_name: "CategoryOffering"
    has_many :visible_offerings, through: :visible_category_offerings,
                                 class_name: "Offering", source: :offering

    validates :curriculum_category, uniqueness: {
      scope: %i(semester_id user_id)
    }

    scope :completed, lambda {
      where(completed: true).includes(:curriculum_category, :courses)
    }
    scope :incompleted, lambda {
      where(completed: false).includes(
        :curriculum_category, offerings: %i(course days_time user),
      )
    }
  end
end

app/models/schedule/category_course.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedule_category_courses
#
#  id          :integer          not null, primary key
#  category_id :integer
#  course_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Schedule
  class CategoryCourse < ApplicationRecord
    belongs_to :category
    belongs_to :course

    validates :course, uniqueness: { scope: :category_id }
  end
end

app/models/schedule/category_offering.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedule_category_offerings
#
#  id          :integer          not null, primary key
#  offering_id :integer
#  category_id :integer
#  hidden      :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Schedule::CategoryOffering < ApplicationRecord
  belongs_to :offering
  belongs_to :category

  scope :visible, -> { where(hidden: false) }
  scope :hidden,  -> { where(hidden: true)  }
end

app/models/schedules/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules_categories
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  curriculum_category_id :integer
#  semester_id            :integer
#  completed              :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

module Schedules
  class Category < ApplicationRecord
    include SemesterHelpers

    default_scope { order(:curriculum_category_id) }

    belongs_to :user
    belongs_to :curriculum_category

    has_many :category_courses, dependent: :destroy
    has_many :courses, through: :category_courses
    has_many :category_offerings, dependent: :destroy
    has_many :offerings, through: :category_offerings

    validates :curriculum_category_id, uniqueness: {
      scope: %i(semester_id user_id)
    }

    def self.table_name_prefix
      "schedules_"
    end

    def category_offerings_by_course
      category_offerings.group_by(&:course)
    end
  end
end

app/models/schedules/category_course.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules_category_courses
#
#  id          :integer          not null, primary key
#  category_id :integer
#  course_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module Schedules
  class CategoryCourse < ApplicationRecord
    belongs_to :category
    belongs_to :course

    validates :course_id, uniqueness: { scope: :category_id }

    def self.table_name_prefix
      "schedules_"
    end
  end
end

app/models/schedules/category_offering.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedules_category_offerings
#
#  id          :integer          not null, primary key
#  offering_id :integer
#  category_id :integer
#  hidden      :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module Schedules
  class CategoryOffering < ApplicationRecord
    default_scope { order(:offering_id) }

    belongs_to :offering
    belongs_to :category
    has_one :curriculum_category, through: :category
    delegate :course, to: :offering

    scope :visible, -> { where(hidden: false) }
    scope :hidden,  -> { where(hidden: true)  }

    def self.table_name_prefix
      "schedules_"
    end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  authorize_resource

  def index
    schedules_categories = current_user.schedules_categories.for_semester(
      current_semester
    ).eager_load(
      :curriculum_category, :courses,
      category_offerings: [offering: %i(course days_time user)]
    )

    @completed_categories = schedules_categories.select(&:completed?)
    @incomplete_categories = schedules_categories.reject(&:completed?)
    @schedules = current_user.offerings.map(&:id)
  end

  def create
    schedule = current_user.schedules.new(
      offering_id: params[:offering_id], semester_id: current_semester_id
    )
    @service = Schedules::Create.new(
      schedule, current_user, current_semester_id
    )
    @service.perform

    respond_to do |format|
      format.js
    end
  end

  def destroy
    schedule = current_user.schedules.find_by(
      offering_id: params[:id], semester_id: current_semester_id
    )

    @service = Schedules::Destroy.new(
      schedule, current_user, current_semester_id
    )
    @service.perform

    respond_to do |format|
      format.js
    end
  end
end

app/views/schedules/create.js.erb
<% if @service.saved? %>
  <% @service.modified.each do |offering_id| %>
    $("[data-offering-id=<%= offering_id %>] input")[0].disabled = true;
  <% end %>
  var element = $("[data-offering-id=<%= @service.schedule.offering_id %>] a");
  element.data("method", "delete");
  element.attr("href", "<%= schedule_path(@service.schedule.offering_id) %>");
  element.find("input")[0].checked = true;
<% end %>

app/views/schedules/destroy.js.erb
<% if @service.destroyed? %>
  <% @service.modified.each do |offering_id| %>
    $("[data-offering-id=<%= offering_id %>] input")[0].disabled = false;
  <% end %>
  var element = $("[data-offering-id=<%= @service.schedule.offering_id %>] a");
  element.data("method", "post");
  element.attr("href", "<%= schedules_path(offering_id: @service.schedule.offering_id) %>");
  element.find("input")[0].checked = false;
<% end %>

app/views/schedules/index.haml
- content_for :title, "Schedule"

.horizontal.wrap.layout.around-justified.mt-3
  .container
    - @incomplete_categories.each do |schedule_category|
      .layout.vertical.center.mx-1
        .mdc-typography--subheading2.w-100
          = schedule_category.curriculum_category.display
        .mdc-card.white.w-100.mb-5
          .mdc-list
            - if schedule_category.offerings.blank?
              .mdc-list-item.danger-text No courses are being offered
            - else
              - schedule_category.offerings.group_by(&:course).each do |course, course_offerings|
                .mdc-list-item= course.pretty_course
                - course_offerings.each do |offering|
                  - if !@schedules.to_a.include? offering
                    = link_to schedules_path(offering_id: offering.id),
                              method: :post, remote: true, class: "mdc-list-item" do
                      = mdc_check_box_tag(nil, "1", false)
                      = offering.display
                  - else
                    = link_to schedule_path(offering), method: :delete, remote: true, class: "mdc-list-item" do
                      = mdc_check_box_tag(nil, "1", false)
            - if schedule_category.courses.present?
              .mdc-list-divider{ role: :separator }
            - schedule_category.courses.each do |course|
              .mdc-list-item
                .mdc-list-item__text= course.pretty_course

  .container
    - @completed_categories.each do |schedule_category|
      .mdc-typography--subheading2.layout.horizontal.start-justified.w-100
        = schedule_category.curriculum_category.display
        .flex
        .success-text Completed
      .mdc-card.white.mb-5
        .mdc-list
          - schedule_category.courses.each do |course|
            .mdc-list-item
              .mdc-list-item__text= course.pretty_course

- unless current_user.schedule_approval
  = link_to user_schedule_approvals_path(current_user),
            method: :post, data: { confirm: "Send to advisor for approval?"} do
    %button.mdl-button.mdl-js-button.mdl-button--fab.edit-fab.fixed
      %i.material-icons check

app/views/schedules/index.html.haml
- content_for :title, "Schedule"
- content_for :active_tab, :schedule

.horizontal.wrap.layout.around-justified.mt-3
  .container
    - @incomplete_categories.each do |schedules_category|
      .layout.vertical.center.mx-1
        .mdc-typography--subheading2.w-100
          = schedules_category.curriculum_category.display
        .mdc-card.white.w-100.mb-5
          .mdc-list
            - if schedules_category.category_offerings.blank?
              .mdc-list-item.danger-text No courses are being offered
            - else
              - schedules_category.category_offerings_by_course.each do |course, category_offerings|
                = link_to course, class: "mdc-list-item w-100 with-ripple" do
                  .mdc-list-item__text
                    .mdc-list-item__text__primary= course.pretty_course
                  = material_icon.chevron_right.css_class("mdc-list-item__end-detail")
                - category_offerings.each do |category_offering|
                  .layout.horizontal.center{ data: { offering_id: category_offering.offering_id } }
                    - if @schedules.exclude?(category_offering.offering_id)
                      = link_to schedules_path(offering_id: category_offering.offering_id),
                                method: :post, remote: true, class: "mdc-list-item" do
                        = mdc_check_box_tag(category_offering.hidden)
                    - else
                      = link_to schedule_path(category_offering.offering), method: :delete,
                          remote: true, class: "mdc-list-item" do
                        = mdc_check_box_tag(false, true)
                    = category_offering.offering.display
            - if schedules_category.courses.present?
              .mdc-list-divider{ role: :separator }
            - schedules_category.courses.each do |course|
              .mdc-list-item
                .mdc-list-item__text= course.pretty_course

  .container
    - @completed_categories.each do |schedules_category|
      .mdc-typography--subheading2.layout.horizontal.start-justified.w-100
        = schedules_category.curriculum_category.display
        .flex
        .success-text Completed
      .mdc-card.white.mb-5
        .mdc-list
          - schedules_category.courses.each do |course|
            .mdc-list-item
              .mdc-list-item__text= course.pretty_course

- if approve_schedule?
  = link_to user_schedule_approvals_path(current_user),
      class: "mdc-fab material-icons new-fab app-fab--absolute",
      "data-mdc-auto-init" => "MDCRipple",
      method: :post, data: { confirm: "Send to advisor for approval?" } do
    %span.mdc-fab__icon check