config/routes.rb
# frozen_string_literal: true

def user?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && !warden_req.user.advisor?
end

def advisor?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && warden_req.user.advisor?
end

Rails.application.routes.draw do
  resources :semesters, only: :update

  resources :majors do
    resources :curriculum_categories, except: :index
  end

  resources :courses do
    resources :offerings, except: :show
  end

  namespace :offerings do
    post :import
  end

  devise_for :users, controllers: {
    registrations: :registrations, sessions: :sessions
  }
  devise_scope :user do
    authenticated :user do
      root "work_schedules#index", constraints: ->(request) { user?(request) }
      root "users#index", constraints: ->(request) { advisor?(request) }
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :transcripts, only: %i(index create destroy new),
                          path: :transcript
  resources :work_schedules, only: %i(create index destroy), path: :calendar
  resources :schedules, only: %i(index create destroy), path: :schedule

  resources :users, only: %i(index show) do
    resources :schedule_approvals, only: %i(create update)
  end
end

app/models/major.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: majors
#
#  id         :integer          not null, primary key
#  major      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Major < ApplicationRecord
  validates :major, uniqueness: true, presence: true

  has_many :major_categories, -> { where minor: false },
           class_name: "CurriculumCategory"
  has_many :minor_categories, -> { where minor: true },
           class_name: "CurriculumCategory"
  has_many :categories, class_name: "CurriculumCategory"
end

app/controllers/majors_controller.rb
# frozen_string_literal: true

class MajorsController < ApplicationController
  load_and_authorize_resource

  def index
    @majors = Major.order(:major)
  end

  def show
  end

  def new
    @major = Major.new
  end

  def edit
  end

  def create
    @major = Major.new(major_params)

    if @major.save
      redirect_to majors_path, notice: "Major was successfully created"
    else
      render :new
    end
  end

  def update
    if @major.update(major_params)
      redirect_to majors_path, notice: "Major was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @major.destroy

    redirect_to majors_path, notice: "Major was successfully destroyed"
  end

  private

  def major_params
    params.require(:major).permit(:major)
  end
end

app/views/majors/_form.html.haml
= form_for major, html: { class: "layout vertical center-center" } do |f|
  .mt-1.mb-2= f.text_field :major, label: "Name", required: true
  = f.submit

app/views/majors/edit.haml
- content_for :title, "Majors"
- content_for :back_url, major_path(@major)

= render "form", major: @major

app/views/majors/edit.html.haml
:ruby
  content_for :title, "Edit Major"
  content_for :back_url, major_path(@major)
  content_for :active_tab, :majors

= render "form", major: @major

app/views/majors/index.haml
- content_for :title, "Majors"

.layout.vertical.center.majors-index
  %p
    Click on a major to modify it or
    the FAB in the bottom right to add a new major.

  .mdc-card{ style: "width: 400px;max-width: 90%;margin-bottom: 40px;background:#fff;"}
    .mdc-list
      - @majors.each do |major|
        = link_to major, class: "mdc-list-item", style: "width: 100%;", "data-mdc-auto-init" => "MDCRipple" do
          .mdc-list-item__text= major.major
          %i.mdc-list-item__end-detail.material-icons
            chevron_right

= fab new_major_path

app/views/majors/index.html.haml
- content_for :title, "Majors"
- content_for :active_tab, :majors

.layout.vertical.center.mt-3
  .container
    %p.center-text.mt-0.mb-3
      Click on the FAB in the bottom right to add a new major. Alternatively,
      click on a major to modify it, or see its curriculum categories.

    .mdc-card.white.mb-5
      .mdc-list
        - @majors.each do |major|
          = link_to major, class: "mdc-list-item w-100 with-ripple" do
            .mdc-list-item__text= major.major
            = material_icon.chevron_right.css_class("mdc-list-item__end-detail")

= fab new_major_path

app/views/majors/new.haml
- content_for :title, "Majors"
- content_for :back_url, majors_path

= render "form", major: @major

app/views/majors/new.html.haml
:ruby
  content_for :title, "New Major"
  content_for :back_url, majors_path
  content_for :active_tab, :majors

= render "form", major: @major

app/views/majors/show.html.haml
:ruby
  content_for :title, "Majors"
  content_for :back_url, majors_path
  content_for :active_tab, :majors

.layout.vertical.center.mt-3
  .container
    .mdc-card.white
      %section.mdc-card__primary
        %h1.mdc-card__title.mdc-card__title--large.layout.horizontal
          = @major.major
          .flex
          = overflow_menu Major, edit_link: edit_major_path(@major),
                                 destroy_link: major_path(@major)

      %section.mdc-card__actions
        = link_to "New Category", new_major_curriculum_category_path(@major),
            class: "mdc-button mdc-button--compact mdc-card__action"

  - if @major.major_categories.empty?
    .mdc-typography--subheading2.mt-5 No Major Categories
  - else
    .mdc-typography--subheading2.mt-5.container
      Major Categories
    .mdc-card.container.white
      .mdc-list
        - @major.major_categories.each do |category|
          = link_to major_curriculum_category_path(@major, category),
              class: "with-ripple mdc-list-item w-100" do
            .mdc-list-item__text= category.category
            %i.mdc-list-item__end-detail.material-icons
              chevron_right

  - if @major.minor_categories.empty?
    .mdc-typography--subheading2.mt-5 No Minor Categories
  - else
    .mdc-typography--subheading2.mt-5.container
      Minor Categories
    .mdc-card.mb-5.container.white
      .mdc-list
        - @major.minor_categories.each do |category|
          = link_to major_curriculum_category_path(@major, category),
              class: "with-ripple mdc-list-item w-100" do
            .mdc-list-item__text= category.category
            %i.mdc-list-item__end-detail.material-icons
              chevron_right