config/routes.rb
# frozen_string_literal: true

def user?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && !warden_req.user.advisor?
end

def advisor?(request)
  warden_req = request.env["warden"]
  warden_req.authenticate? && warden_req.user.advisor?
end

Rails.application.routes.draw do
  resources :semesters, only: :update

  resources :majors do
    resources :curriculum_categories, except: :index
  end

  resources :courses do
    resources :offerings, except: :show
  end

  namespace :offerings do
    post :import
  end

  devise_for :users, controllers: {
    registrations: :registrations, sessions: :sessions
  }
  devise_scope :user do
    authenticated :user do
      root "work_schedules#index", constraints: ->(request) { user?(request) }
      root "users#index", constraints: ->(request) { advisor?(request) }
    end

    unauthenticated do
      root "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :transcripts, only: %i(index create destroy new),
                          path: :transcript
  resources :work_schedules, only: %i(create index destroy), path: :calendar
  resources :schedules, only: %i(index create destroy), path: :schedule

  resources :users, only: %i(index show) do
    resources :schedule_approvals, only: %i(create update)
  end
end

app/views/layouts/_bottom_navigation.html.haml
.layout.horizontal.center-center#drawer
  - if current_user&.advisor?
    = drawer_link(users_path, "people", "Students", active_tab)
    = drawer_link(courses_path, "local_library", "Courses", active_tab)
    = drawer_link(majors_path, "bookmark", "Majors", active_tab)
  - else
    = drawer_link(transcripts_path, "description", "Transcript", active_tab)
    = drawer_link(work_schedules_path, "access_time", "Calendar", active_tab)
    = drawer_link(schedules_path, "event", "Schedule", active_tab)

app/views/layouts/_drawer.html.haml
.layout.horizontal.around-justified.center#drawer{ "data-turbolinks-permanent" => true }
  - if current_user&.advisor?
    = drawer_link(users_path, "people", "Students", active_tab)
    = drawer_link(courses_path, "local_library", "Courses", active_tab)
    = drawer_link(majors_path, "bookmark", "Majors", active_tab)
  - else
    = drawer_link(transcripts_path, "description", "Transcript", active_tab)
    = drawer_link(work_schedules_path, "access_time", "Calendar", active_tab)
    = drawer_link(schedules_path, "event", "Schedule", active_tab)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= render_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag "callogo2.png"
    %link{ href: image_url("callogo2.png"), rel: "apple-touch-icon" }/
    %meta{ content: "yes", name: "mobile-web-app-capable" }/
    %meta{ content: "yes", name: "apple-mobile-web-app-capable" }/
    %meta{ content: "minimal-ui, width=device-width,
      height=device-height, initial-scale=1.0, maximum-scale=1.0", name: "viewport" }/
    %meta{ content: "#3f51b5", name: "theme-color" }/

  %body.vertical.layout
    = snackbar_notice(notice || alert, ("pushup" if signed_in? && yield(:active_tab).present?).to_s)

    - if current_user
      %header.mdc-toolbar
        .mdc-toolbar__row
          %section.mdc-toolbar__section.mdc-toolbar__section--align-start.flex-2
            = render_back_url(yield(:back_url))
          %section.mdc-toolbar__section.mdc-toolbar__section--align-end.layout.center
            = yield(:toolbar)
            = link_to edit_user_registration_path, class: "ml-2 black-text d-flex" do
              = material_icon.settings
            = link_to destroy_user_session_path, method: :delete, class: "mx-2 black-text d-flex" do
              = material_icon.exit_to_app

    %main.mb-10= yield

    - if signed_in? && yield(:active_tab).present?
      = render "layouts/bottom_navigation", active_tab: yield(:active_tab)